modLoader="javafml"
loaderVersion="[47,)"
license="All Rights Reserved"

[[mods]]
modId="power"
version="3.2.2"
displayName="Keepers of the Stones"
displayURL="https://power-umc.ru/minecraft-java-edition/mods/6-keepers-of-the-stones.html"
logoFile="logo.png"
credits="Created by Environment Stuidos"
authors="UMC"
description="This mod will add new sources of energy to the world with which you can transform into masters of the elements."

[[dependencies.power]]
    modId="minecraft"
    mandatory=true
    versionRange="[1.20.1]"
    ordering="NONE"
    side="BOTH"


[[dependencies.power]]
    modId="pehkui"
    mandatory=true
    versionRange="[0,)"
    ordering="NONE"
    side="BOTH"

[[dependencies.power]]
    modId="allmods"
    mandatory=false
    versionRange="[0,)"
    ordering="NONE"
    side="BOTH"

[[dependencies.power]]
    modId="power_dimensions"
    mandatory=false
    versionRange="[0,)"
    ordering="NONE"
    side="BOTH"
